<?php

namespace Birds\ObservationsBundle\Repository;

/**
 * BirdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdsRepository extends \Doctrine\ORM\EntityRepository
{


}
