<?php

namespace Birds\ObservationsBundle\Repository;

/**
 * BirdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @return array
     */
    public function getAllByArray()
    {
        $br= $this->_em->createQueryBuilder()
            ->select('b.lbNom')
            ->from('BirdsObservationsBundle:Birds','b')
            ->orderBy('b.lbNom','ASC');

        return $br->getQuery()->getScalarResult();

    }

}
