<?php

namespace Birds\ObservationsBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{


    public function findLastValid($number)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('o')
            ->from('BirdsObservationsBundle:Observation','o')
            ->where('o.valid = :val')
            ->setParameter('val',true)
            ->orderBy('o.id','DESC')
            ->setMaxResults($number);
        return $qb->getQuery()->getResult();

    }
}
