<?php

namespace Birds\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllByUser(\AppBundle\Entity\User $user)
  {
    $qb = $this->_em->createQueryBuilder();
    $qb
    ->select('a')
    ->from('BirdsBlogBundle:Article', 'a')
    ->where('a.user = :userId')
    ->setParameter(':userId', $user);
    return $qb
    ->getQuery()
    ->getResult();
  }
  
  public function getTotalCount(\AppBundle\Entity\User $user)
  {
    $qb = $this->_em->createQueryBuilder();
    $qb
    ->select('COUNT(a)')
    ->from('BirdsBlogBundle:Article', 'a')
    ->where('a.user = :userId')
    ->setParameter(':userId', $user);
    return $qb
    ->getQuery()->getSingleScalarResult();
  }
  
    /**
     * @param $pageNumber
     * @return mixed : array
     */
    public function getByPage($pageNumber, \AppBundle\Entity\User $user, $limit=4)
    {
        $results['nombreResultat'] =  $this->getTotalCount($user);
        $results['nombrePage'] = ceil($results['nombreResultat']/$limit);//Total number of page per 25 Users
        $page = intval($pageNumber);
        if($results['nombrePage'] < $page)     //25 Users per page
            $page = ceil($results['nombreResultat']/$limit);    //
        if($page<1)
            $page=1;
        $results["page"]= $page;
        $qb = $this->_em->createQueryBuilder('a')->select('a')
            ->from('BirdsBlogBundle:Article', 'a')
            ->where('a.user = :userId')
            ->setParameter(':userId', $user);
            
        //Order by:
        $qb->orderBy('a.creationDate');
        
        $qb->setFirstResult(($page-1)*$limit)->setMaxResults($limit);
        $results['results']= $qb->getQuery()->getResult();
        return $results;
    }
    
    public function TotalCount()
    {
    $qb = $this->_em->createQueryBuilder();
    $qb
    ->select('COUNT(a)')
    ->from('BirdsBlogBundle:Article', 'a');
//    ->where('a.user = :userId')
//    ->setParameter(':userId', $user);
    return $qb
    ->getQuery()->getSingleScalarResult();
    }
  
    /**
     * @param $pageNumber
     * @return mixed : array
     */
    public function getPage($pageNumber, $limit=4)
    {
        $results['nombreResultat'] =  $this->TotalCount();
        $results['nombrePage'] = ceil($results['nombreResultat']/$limit);//Total number of page per 25 Users
        $page = intval($pageNumber);
        if($results['nombrePage'] < $page)     //25 Users per page
            $page = ceil($results['nombreResultat']/$limit);    //
        if($page<1)
            $page=1;
        $results["page"]= $page;
        $qb = $this->_em->createQueryBuilder('a')->select('a')
            ->from('BirdsBlogBundle:Article', 'a');
//            ->where('a.user = :userId')
//            ->setParameter(':userId', $user);
            
        //Order by:
        $qb->orderBy('a.creationDate');
        
        $qb->setFirstResult(($page-1)*$limit)->setMaxResults($limit);
        $results['results']= $qb->getQuery()->getResult();
        return $results;
    }
}
