easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

birds_blog:
    resource: "@BirdsBlogBundle/Resources/config/routing/article.yml"
    prefix:   /Blog

birds_observations:
    resource: "@BirdsObservationsBundle/Resources/config/routing.yml"
    prefix:   /Obs

app:
    resource: '@AppBundle/Resources/config/routing.yml'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"