services:
    birdsObservations.validator:
        class: Birds\ObservationsBundle\ValidateData\Validator

    birdsObservations.pager:
        class: Birds\ObservationsBundle\Pager\Pager

    birds.map:
        class: Birds\ObservationsBundle\Services\Mapper\Mapper